# CMake generated Testfile for 
# Source directory: /home/rmlarsen/eigen/rmlarsen3/eigen-new/unsupported/test/GPU
# Build directory: /home/rmlarsen/eigen/rmlarsen3/eigen-new/build-gpu/unsupported/test/GPU
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(device_matrix "/home/rmlarsen/eigen/rmlarsen3/eigen-new/build-gpu/unsupported/test/GPU/device_matrix")
set_tests_properties(device_matrix PROPERTIES  LABELS "Unsupported;Official;gpu" SKIP_RETURN_CODE "77" _BACKTRACE_TRIPLES "/home/rmlarsen/eigen/rmlarsen3/eigen-new/cmake/EigenTesting.cmake;133;add_test;/home/rmlarsen/eigen/rmlarsen3/eigen-new/cmake/EigenTesting.cmake;240;ei_add_test_internal;/home/rmlarsen/eigen/rmlarsen3/eigen-new/unsupported/test/GPU/CMakeLists.txt;28;ei_add_test;/home/rmlarsen/eigen/rmlarsen3/eigen-new/unsupported/test/GPU/CMakeLists.txt;61;ei_add_gpu_test;/home/rmlarsen/eigen/rmlarsen3/eigen-new/unsupported/test/GPU/CMakeLists.txt;0;")
add_test(cufft_1 "/home/rmlarsen/eigen/rmlarsen3/eigen-new/build-gpu/unsupported/test/GPU/cufft_1")
set_tests_properties(cufft_1 PROPERTIES  LABELS "Unsupported;Official;gpu" SKIP_RETURN_CODE "77" _BACKTRACE_TRIPLES "/home/rmlarsen/eigen/rmlarsen3/eigen-new/cmake/EigenTesting.cmake;133;add_test;/home/rmlarsen/eigen/rmlarsen3/eigen-new/cmake/EigenTesting.cmake;235;ei_add_test_internal;/home/rmlarsen/eigen/rmlarsen3/eigen-new/unsupported/test/GPU/CMakeLists.txt;28;ei_add_test;/home/rmlarsen/eigen/rmlarsen3/eigen-new/unsupported/test/GPU/CMakeLists.txt;80;ei_add_gpu_test;/home/rmlarsen/eigen/rmlarsen3/eigen-new/unsupported/test/GPU/CMakeLists.txt;0;")
add_test(cufft_2 "/home/rmlarsen/eigen/rmlarsen3/eigen-new/build-gpu/unsupported/test/GPU/cufft_2")
set_tests_properties(cufft_2 PROPERTIES  LABELS "Unsupported;Official;gpu" SKIP_RETURN_CODE "77" _BACKTRACE_TRIPLES "/home/rmlarsen/eigen/rmlarsen3/eigen-new/cmake/EigenTesting.cmake;133;add_test;/home/rmlarsen/eigen/rmlarsen3/eigen-new/cmake/EigenTesting.cmake;235;ei_add_test_internal;/home/rmlarsen/eigen/rmlarsen3/eigen-new/unsupported/test/GPU/CMakeLists.txt;28;ei_add_test;/home/rmlarsen/eigen/rmlarsen3/eigen-new/unsupported/test/GPU/CMakeLists.txt;80;ei_add_gpu_test;/home/rmlarsen/eigen/rmlarsen3/eigen-new/unsupported/test/GPU/CMakeLists.txt;0;")
add_test(cusparse_spmv_1 "/home/rmlarsen/eigen/rmlarsen3/eigen-new/build-gpu/unsupported/test/GPU/cusparse_spmv_1")
set_tests_properties(cusparse_spmv_1 PROPERTIES  LABELS "Unsupported;Official;gpu" SKIP_RETURN_CODE "77" _BACKTRACE_TRIPLES "/home/rmlarsen/eigen/rmlarsen3/eigen-new/cmake/EigenTesting.cmake;133;add_test;/home/rmlarsen/eigen/rmlarsen3/eigen-new/cmake/EigenTesting.cmake;235;ei_add_test_internal;/home/rmlarsen/eigen/rmlarsen3/eigen-new/unsupported/test/GPU/CMakeLists.txt;28;ei_add_test;/home/rmlarsen/eigen/rmlarsen3/eigen-new/unsupported/test/GPU/CMakeLists.txt;86;ei_add_gpu_test;/home/rmlarsen/eigen/rmlarsen3/eigen-new/unsupported/test/GPU/CMakeLists.txt;0;")
add_test(cusparse_spmv_2 "/home/rmlarsen/eigen/rmlarsen3/eigen-new/build-gpu/unsupported/test/GPU/cusparse_spmv_2")
set_tests_properties(cusparse_spmv_2 PROPERTIES  LABELS "Unsupported;Official;gpu" SKIP_RETURN_CODE "77" _BACKTRACE_TRIPLES "/home/rmlarsen/eigen/rmlarsen3/eigen-new/cmake/EigenTesting.cmake;133;add_test;/home/rmlarsen/eigen/rmlarsen3/eigen-new/cmake/EigenTesting.cmake;235;ei_add_test_internal;/home/rmlarsen/eigen/rmlarsen3/eigen-new/unsupported/test/GPU/CMakeLists.txt;28;ei_add_test;/home/rmlarsen/eigen/rmlarsen3/eigen-new/unsupported/test/GPU/CMakeLists.txt;86;ei_add_gpu_test;/home/rmlarsen/eigen/rmlarsen3/eigen-new/unsupported/test/GPU/CMakeLists.txt;0;")
add_test(cusparse_spmv_3 "/home/rmlarsen/eigen/rmlarsen3/eigen-new/build-gpu/unsupported/test/GPU/cusparse_spmv_3")
set_tests_properties(cusparse_spmv_3 PROPERTIES  LABELS "Unsupported;Official;gpu" SKIP_RETURN_CODE "77" _BACKTRACE_TRIPLES "/home/rmlarsen/eigen/rmlarsen3/eigen-new/cmake/EigenTesting.cmake;133;add_test;/home/rmlarsen/eigen/rmlarsen3/eigen-new/cmake/EigenTesting.cmake;235;ei_add_test_internal;/home/rmlarsen/eigen/rmlarsen3/eigen-new/unsupported/test/GPU/CMakeLists.txt;28;ei_add_test;/home/rmlarsen/eigen/rmlarsen3/eigen-new/unsupported/test/GPU/CMakeLists.txt;86;ei_add_gpu_test;/home/rmlarsen/eigen/rmlarsen3/eigen-new/unsupported/test/GPU/CMakeLists.txt;0;")
add_test(cusparse_spmv_4 "/home/rmlarsen/eigen/rmlarsen3/eigen-new/build-gpu/unsupported/test/GPU/cusparse_spmv_4")
set_tests_properties(cusparse_spmv_4 PROPERTIES  LABELS "Unsupported;Official;gpu" SKIP_RETURN_CODE "77" _BACKTRACE_TRIPLES "/home/rmlarsen/eigen/rmlarsen3/eigen-new/cmake/EigenTesting.cmake;133;add_test;/home/rmlarsen/eigen/rmlarsen3/eigen-new/cmake/EigenTesting.cmake;235;ei_add_test_internal;/home/rmlarsen/eigen/rmlarsen3/eigen-new/unsupported/test/GPU/CMakeLists.txt;28;ei_add_test;/home/rmlarsen/eigen/rmlarsen3/eigen-new/unsupported/test/GPU/CMakeLists.txt;86;ei_add_gpu_test;/home/rmlarsen/eigen/rmlarsen3/eigen-new/unsupported/test/GPU/CMakeLists.txt;0;")
add_test(cg_1 "/home/rmlarsen/eigen/rmlarsen3/eigen-new/build-gpu/unsupported/test/GPU/cg_1")
set_tests_properties(cg_1 PROPERTIES  LABELS "Unsupported;Official;gpu" SKIP_RETURN_CODE "77" _BACKTRACE_TRIPLES "/home/rmlarsen/eigen/rmlarsen3/eigen-new/cmake/EigenTesting.cmake;133;add_test;/home/rmlarsen/eigen/rmlarsen3/eigen-new/cmake/EigenTesting.cmake;235;ei_add_test_internal;/home/rmlarsen/eigen/rmlarsen3/eigen-new/unsupported/test/GPU/CMakeLists.txt;28;ei_add_test;/home/rmlarsen/eigen/rmlarsen3/eigen-new/unsupported/test/GPU/CMakeLists.txt;88;ei_add_gpu_test;/home/rmlarsen/eigen/rmlarsen3/eigen-new/unsupported/test/GPU/CMakeLists.txt;0;")
add_test(cg_2 "/home/rmlarsen/eigen/rmlarsen3/eigen-new/build-gpu/unsupported/test/GPU/cg_2")
set_tests_properties(cg_2 PROPERTIES  LABELS "Unsupported;Official;gpu" SKIP_RETURN_CODE "77" _BACKTRACE_TRIPLES "/home/rmlarsen/eigen/rmlarsen3/eigen-new/cmake/EigenTesting.cmake;133;add_test;/home/rmlarsen/eigen/rmlarsen3/eigen-new/cmake/EigenTesting.cmake;235;ei_add_test_internal;/home/rmlarsen/eigen/rmlarsen3/eigen-new/unsupported/test/GPU/CMakeLists.txt;28;ei_add_test;/home/rmlarsen/eigen/rmlarsen3/eigen-new/unsupported/test/GPU/CMakeLists.txt;88;ei_add_gpu_test;/home/rmlarsen/eigen/rmlarsen3/eigen-new/unsupported/test/GPU/CMakeLists.txt;0;")
