#!/bin/bash

if [[ $# != 1 || $1 == *help ]]
then
  echo "usage: $0 regexp"
  echo "  Builds tests matching the regexp."
  echo "  The EIGEN_MAKE_ARGS environment variable allows to pass args to 'make'."
  echo "    For example, to launch 5 concurrent builds, use EIGEN_MAKE_ARGS='-j5'"
  exit 0
fi

TESTSLIST="clz
rand
realview
meta
lru_cache
maxsizevector
numext
sizeof
dynalloc
nomalloc
first_aligned
type_alias
nullary
mixingtypes
float_conversion
io
packetmath
packet_segment
vectorization_logic
basicstuff
constexpr
constructor
linearstructure
integer_types
unalignedcount
exceptions
redux
visitor
block
corners
symbolic_index
indexed_view
reshape
swap
resize
no_automatic_resizing
conservative_resize
product_small
product_large
product_extra
diagonalmatrices
diagonalview
skew_symmetric_matrix3
adjoint
diagonal
miscmatrices
commainitializer
smallvectors
mapped_matrix
mapstride
unaryview
mapstaticmethods
array_cwise
matrix_cwise
array_for_matrix
array_replicate
concat
array_reverse
ref
is_same_dense
triangular
selfadjoint
product_selfadjoint
product_symm
product_syrk
product_trmv
product_trmm
product_trsolve
product_mmtr
product_notemporary
product_threaded
stable_norm
permutationmatrices
bandmatrix
cholesky
bunchkaufman
condition_estimator
lu
determinant
inverse
qr
qr_colpivoting
qr_rand_colpivoting
qr_fullpivoting
upperbidiagonalization
hessenberg
schur_real
schur_complex
eigensolver_selfadjoint
tridiagonal_eigensolver
eigensolver_generic
eigensolver_complex
real_qz
complex_qz
eigensolver_generalized_real
jacobi
jacobisvd
bdcsvd
householder
geo_orthomethods
geo_quaternion
geo_eulerangles
geo_parametrizedline
geo_alignedbox
geo_hyperplane
geo_transformations
geo_homogeneous
geo_misc
stdvector
stdvector_overload
stdlist
stdlist_overload
stddeque
stddeque_overload
block_sparse_matrix
sparse_basic
sparse_block
sparse_vector
sparse_product
sparse_threaded_product
sparse_ref
sparse_solvers
sparse_permutations
simplicial_cholesky
conjugate_gradient
incomplete_cholesky
incomplete_LUT
bicgstab
lscg
lsmr
gmres
dgmres
minres
idrs
bicgstabl
idrstabl
sparselu
sparseqr
sparse_ordering
umeyama
nesting_ops
nestbyvalue
zerosized
dontalign
evaluators
sizeoverflow
prec_inverse_4x4
vectorwiseop
special_numbers
rvalue_types
dense_storage
ctorleak
inplace_decomposition
half_float
bfloat16_float
array_of_string
num_dimensions
stl_iterators
blasutil
random_matrix
initializer_list_construction
diagonal_matrix_variadic_ctor
serializer
special_members
tuple_test
structured_bindings
threads_eventcount
threads_runqueue
threads_non_blocking_thread_pool
threads_fork_join
assignment_threaded
packetmath_fastmath
fastmath
bdcsvd_fastmath
stable_norm_fastmath
gpu_example
gpu_basic
NonLinearOptimization
NumericalDiff
autodiff_scalar
autodiff
BVH
matrix_exponential
matrix_function
matrix_power
matrix_square_root
alignedvector3
FFT
EulerAngles
NNLS
sparse_extra
FFTW
polynomialsolver
polynomialutils
splines
levenberg_marquardt
kronecker_product
structured_matrices
bessel_functions
special_functions
special_packetmath
tensor_argmax
tensor_assign
tensor_block_access
tensor_block_eval
tensor_block_io
tensor_broadcasting
tensor_casts
tensor_chipping
tensor_comparisons
tensor_concatenation
tensor_const
tensor_contraction
tensor_cost_model
tensor_convolution
tensor_custom_index
tensor_custom_op
tensor_dimension
tensor_empty
tensor_executor
tensor_expr
tensor_fft
tensor_fixed_size
tensor_forced_eval
tensor_generator
tensor_ifft
tensor_image_patch
tensor_index_list
tensor_inflation
tensor_intdiv
tensor_io
tensor_layout_swap
tensor_lvalue
tensor_map
tensor_math
tensor_mixed_indices
tensor_morphing
tensor_move
tensor_notification
tensor_of_complex
tensor_of_const_values
tensor_of_strings
tensor_padding
tensor_patch
tensor_random
tensor_reverse
tensor_reduction
tensor_ref
tensor_roll
tensor_roundings
tensor_scan
tensor_shuffling
tensor_simple
tensor_special_members
tensor_striding
tensor_sugar
tensor_thread_local
tensor_thread_pool
tensor_trace
tensor_volume_patch
tensor_symmetry
tensor_uint128
tensor_complex_gpu
tensor_complex_cwise_ops_gpu
tensor_reduction_gpu
tensor_argmax_gpu
tensor_cast_float16_gpu
tensor_scan_gpu
tensor_device
tensor_gpu
tensor_contract_gpu
tensor_of_float16_gpu
tensor_random_gpu
device_matrix
cufft
cusparse_spmv
cg
"
targets_to_make=$(echo "$TESTSLIST" | grep -E "$1" | xargs echo)

if [ -n "${EIGEN_MAKE_ARGS:+x}" ]
then
  /usr/bin/ninja $targets_to_make ${EIGEN_MAKE_ARGS}
else
  /usr/bin/ninja $targets_to_make 
fi
exit $?

