# Hexagon DSP cross-compilation builds
# This file is part of Eigen, a lightweight C++ template library
# for linear algebra.
#
# Copyright (C) 2023, The Eigen Authors
#
# This Source Code Form is subject to the terms of the Mozilla
# Public License v. 2.0. If a copy of the MPL was not distributed
# with this file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Base configuration for Hexagon DSP cross-compilation
.build:linux:hexagon:
  extends: .common:linux:cross
  stage: build
  image: ubuntu:20.04
  variables:
    EIGEN_CI_TARGET_ARCH: hexagon
    EIGEN_CI_CROSS_TARGET_TRIPLE: hexagon-unknown-linux-musl
    EIGEN_CI_BUILD_TARGET: buildtests
    EIGEN_CI_HEXAGON_ARCH: v68
    EIGEN_CI_HEXAGON_TOOLCHAIN_VERSION: "20.1.4"
    # Hexagon-specific optimization flags
    EIGEN_CI_HEXAGON_HVX_LENGTH: "128B"
    EIGEN_CI_HEXAGON_FLAGS: "-G0 -fPIC -mhvx"
  before_script:
    - . ci/scripts/common.linux.before_script.sh
    - ./ci/scripts/error-handler.hexagon.sh download_toolchain "$HEXAGON_TOOLCHAIN_URL" "/opt/hexagon-toolchain" "$EIGEN_CI_HEXAGON_TOOLCHAIN_VERSION" || . ci/scripts/setup.hexagon.sh
    - ./ci/scripts/validate.hexagon.sh
  tags:
    - linux
    - eigen-runner
    - cross-compiler
  rules:
    # Run on scheduled builds (nightly)
    - if: $CI_PIPELINE_SOURCE == "schedule" && $CI_PROJECT_NAMESPACE == "libeigen"
    # Run on manual web triggers
    - if: $CI_PIPELINE_SOURCE == "web" && $CI_PROJECT_NAMESPACE == "libeigen"
    # Run on merge requests with hexagon-tests label
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_PROJECT_NAMESPACE == "libeigen" && $CI_MERGE_REQUEST_LABELS =~ "/hexagon-tests/"
  after_script:
    - ./ci/scripts/performance-monitor.hexagon.sh resource_monitor 60 "${EIGEN_CI_BUILDDIR:-.build}" || true
    - ./ci/scripts/alert.hexagon.sh pipeline_success "$(cat ${EIGEN_CI_BUILDDIR:-.build}/build-duration.txt 2>/dev/null || echo '0')" "$(find ${EIGEN_CI_BUILDDIR:-.build} -name '*test*' -executable -type f | wc -l)" || true
  artifacts:
    reports:
      junit: ${EIGEN_CI_BUILDDIR:-.build}/test-results.xml
    paths:
      - ${EIGEN_CI_BUILDDIR:-.build}/*.log
      - ${EIGEN_CI_BUILDDIR:-.build}/performance-*.json
      - ${EIGEN_CI_BUILDDIR:-.build}/optimization-report.txt
      - ${EIGEN_CI_BUILDDIR:-.build}/error-summary.json
      - ${EIGEN_CI_BUILDDIR:-.build}/alerts.log
    expire_in: 1 week
    when: always
  cache:
    key: "hexagon-$CI_COMMIT_REF_SLUG-$EIGEN_CI_HEXAGON_ARCH"
    paths:
      - .cache/ccache/
      - .cache/hexagon-toolchain/
      - ${EIGEN_CI_BUILDDIR}/CMakeCache.txt
      - ${EIGEN_CI_BUILDDIR}/CMakeFiles/
    policy: pull-push

######## Hexagon v68 ############################################################

# Basic Hexagon v68 build
build:linux:hexagon:v68:default:
  extends: .build:linux:hexagon
  variables:
    EIGEN_CI_HEXAGON_ARCH: v68
    EIGEN_CI_ADDITIONAL_ARGS: "-DCMAKE_TOOLCHAIN_FILE=${PWD}/cmake/HexagonToolchain.cmake -DEIGEN_TEST_HEXAGON=ON -DCMAKE_BUILD_TYPE=Release"

# Hexagon v68 with HVX enabled
build:linux:hexagon:v68:hvx:
  extends: build:linux:hexagon:v68:default
  variables:
    EIGEN_CI_ADDITIONAL_ARGS: "-DCMAKE_TOOLCHAIN_FILE=${PWD}/cmake/HexagonToolchain.cmake -DEIGEN_TEST_HEXAGON=ON -DEIGEN_TEST_HVX=ON -DCMAKE_BUILD_TYPE=Release"

# Hexagon v68 with debug symbols
build:linux:hexagon:v68:debug:
  extends: build:linux:hexagon:v68:default
  variables:
    EIGEN_CI_ADDITIONAL_ARGS: "-DCMAKE_TOOLCHAIN_FILE=${PWD}/cmake/HexagonToolchain.cmake -DEIGEN_TEST_HEXAGON=ON -DCMAKE_BUILD_TYPE=Debug"

######## Hexagon v73 ############################################################

# Hexagon v73 (latest architecture)
build:linux:hexagon:v73:default:
  extends: .build:linux:hexagon
  variables:
    EIGEN_CI_HEXAGON_ARCH: v73
    EIGEN_CI_ADDITIONAL_ARGS: "-DCMAKE_TOOLCHAIN_FILE=${PWD}/cmake/HexagonToolchain.cmake -DEIGEN_TEST_HEXAGON=ON -DCMAKE_BUILD_TYPE=Release"

# Hexagon v73 with HVX enabled
build:linux:hexagon:v73:hvx:
  extends: build:linux:hexagon:v73:default
  variables:
    EIGEN_CI_ADDITIONAL_ARGS: "-DCMAKE_TOOLCHAIN_FILE=${PWD}/cmake/HexagonToolchain.cmake -DEIGEN_TEST_HEXAGON=ON -DEIGEN_TEST_HVX=ON -DCMAKE_BUILD_TYPE=Release"

######## Special Builds #########################################################

# Hexagon build with maximum optimization
build:linux:hexagon:v68:optimized:
  extends: build:linux:hexagon:v68:default
  variables:
    EIGEN_CI_ADDITIONAL_ARGS: "-DCMAKE_TOOLCHAIN_FILE=${PWD}/cmake/HexagonToolchain.cmake -DEIGEN_TEST_HEXAGON=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS_RELEASE=-O3"

# Minimal Hexagon build (build-only, no tests)
build:linux:hexagon:v68:minimal:
  extends: .build:linux:hexagon
  variables:
    EIGEN_CI_HEXAGON_ARCH: v68
    EIGEN_CI_BUILD_TARGET: ""  # Build library only
    EIGEN_CI_ADDITIONAL_ARGS: "-DCMAKE_TOOLCHAIN_FILE=${PWD}/cmake/HexagonToolchain.cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF"
  rules:
    # Run on all merge requests for basic validation
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_PROJECT_NAMESPACE == "libeigen" 