# Refined Hexagon DSP CI with Clean Architecture
# Uses CI-focused Dockerfile in eigen-mirror/ci/Dockerfile

# Build Docker images for CI
build:docker:hexagon:
  stage: .pre
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_BUILDKIT: "1"
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    # Build CI-optimized image for x86_64
    - |
      docker buildx build \
        --platform linux/amd64 \
        --build-arg HEXAGON_TOOLCHAIN_VERSION=20.1.4 \
        --tag $CI_REGISTRY_IMAGE/eigen-ci:hexagon-latest \
        --tag $CI_REGISTRY_IMAGE/eigen-ci:hexagon-$CI_COMMIT_SHORT_SHA \
        --file ci/Dockerfile \
        --push \
        .
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_COMMIT_BRANCH == "master"
    - if: $CI_COMMIT_BRANCH == "hexagon_toolchain"
    - if: $CI_COMMIT_BRANCH == "hexagon_toolchain-mirror"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - "ci/Dockerfile"
        - "ci/**/*hexagon*"
        - "cmake/HexagonToolchain.cmake"
  # tags:
  #   - docker
  #   - linux

# Base CI configuration using clean Docker image
.build:linux:hexagon:
  stage: build
  image: $CI_REGISTRY_IMAGE/eigen-ci:hexagon-latest
  variables:
    EIGEN_CI_TARGET_ARCH: hexagon
    EIGEN_CI_CROSS_TARGET_TRIPLE: hexagon-unknown-linux-musl
    EIGEN_CI_BUILD_TARGET: "packetmath_1 packetmath_2 packetmath_3 basicstuff_1 vectorization_logic_1"
    EIGEN_CI_HEXAGON_TOOLCHAIN_VERSION: "20.1.4"
    EIGEN_CI_HEXAGON_HVX_LENGTH: "128B"
  before_script:
    - export CCACHE_DIR=/workspace/.cache/ccache
    - mkdir -p ${CCACHE_DIR}
    - ccache -s
  script:
    - mkdir -p ${EIGEN_CI_BUILDDIR:-.build}
    - cd ${EIGEN_CI_BUILDDIR:-.build}
    - |
      cmake \
        -DCMAKE_TOOLCHAIN_FILE=${PWD}/../cmake/HexagonToolchain.cmake \
        -DCMAKE_BUILD_TYPE=Release \
        -DEIGEN_TEST_HEXAGON=ON \
        -DBUILD_TESTING=ON \
        -DHEXAGON_ARCH=${EIGEN_CI_HEXAGON_ARCH} \
        -GNinja \
        ${EIGEN_CI_ADDITIONAL_ARGS} \
        ..
    - ninja ${EIGEN_CI_BUILD_TARGET}
  after_script:
    - ccache -s
  artifacts:
    paths:
      - ${EIGEN_CI_BUILDDIR:-.build}/
    expire_in: 1 week
    when: always
  cache:
    key: "hexagon-ci-$CI_COMMIT_REF_SLUG-$EIGEN_CI_HEXAGON_ARCH"
    paths:
      - .cache/ccache/
    policy: pull-push
  # tags:
  #   - linux
  #   - eigen-runner

######## Hexagon v73 Builds ############################################

# Standard v73 build (default configuration)
build:linux:hexagon:v73:default:
  extends: .build:linux:hexagon
  variables:
    EIGEN_CI_HEXAGON_ARCH: v73
    EIGEN_CI_BUILDDIR: .build-hexagon-v73-default
    EIGEN_CI_ADDITIONAL_ARGS: "-DCMAKE_BUILD_TYPE=Release"
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_COMMIT_BRANCH == "master"
    - if: $CI_COMMIT_BRANCH == "hexagon_toolchain"
    - if: $CI_COMMIT_BRANCH == "hexagon_toolchain-mirror"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

# HVX-enabled v73 build
build:linux:hexagon:v73:hvx:
  extends: .build:linux:hexagon
  variables:
    EIGEN_CI_HEXAGON_ARCH: v73
    EIGEN_CI_BUILDDIR: .build-hexagon-v73-hvx
    EIGEN_CI_ADDITIONAL_ARGS: "-DCMAKE_BUILD_TYPE=Release -DEIGEN_TEST_HVX=ON"
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_COMMIT_BRANCH == "master"
    - if: $CI_COMMIT_BRANCH == "hexagon_toolchain"
    - if: $CI_COMMIT_BRANCH == "hexagon_toolchain-mirror"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

######## Debug and Development Builds ###############################

# Debug build for development
build:linux:hexagon:v73:debug:
  extends: .build:linux:hexagon
  variables:
    EIGEN_CI_HEXAGON_ARCH: v73
    EIGEN_CI_BUILDDIR: .build-hexagon-v73-debug
    EIGEN_CI_ADDITIONAL_ARGS: "-DCMAKE_BUILD_TYPE=Debug"
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_COMMIT_BRANCH == "master"
    - if: $CI_COMMIT_BRANCH == "hexagon_toolchain"
    - if: $CI_COMMIT_BRANCH == "hexagon_toolchain-mirror"

# Minimal build for quick validation (MR pipeline)
build:linux:hexagon:minimal:
  extends: .build:linux:hexagon
  variables:
    EIGEN_CI_HEXAGON_ARCH: v73
    EIGEN_CI_BUILDDIR: .build-hexagon-minimal
    EIGEN_CI_BUILD_TARGET: ""  # Build library only
    EIGEN_CI_ADDITIONAL_ARGS: "-DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF"
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "hexagon_toolchain"
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "hexagon_toolchain-mirror"
    - if: $CI_PIPELINE_SOURCE == "web" 