checkformat:clangformat:
  stage: checkformat
  image: ubuntu:23.10
  only:
    - merge_requests
  allow_failure: true
  before_script:
    - apt-get update -y
    - apt-get install -y --no-install-recommends git clang-format-17
  script:
    - git branch -v
    - git remote -v
    - git fetch --no-tags --prune --depth=1 origin +refs/heads/master:refs/remotes/origin/master
    - git log --graph --decorate --oneline -n 10
    - git clang-format-17 --diff --commit origin/master
