checkformat:clangformat:
  stage: checkformat
  image: alpine:3.19
  only:
    - merge_requests
  allow_failure: true
  before_script:
    - apk add --no-cache git clang-format clang-format-17
  script:
    - git clang-format-17 --diff --commit ${CI_MERGE_REQUEST_DIFF_BASE_SHA}
