 # Push a nightly tag if the pipeline succeeded.
deploy:tag:
  stage: deploy
  image: ubuntu:latest
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update -y
    - apt-get install -y --no-install-recommends git
  script:
    - git tag nightly master
    - git push $EIGEN_CI_GIT_PUSH_URL master tag nightly
  tags:
    - linux
    - eigen-runner
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $CI_PROJECT_NAMESPACE == "libeigen"
    - if: $CI_PIPELINE_SOURCE == "web" && $CI_PROJECT_NAMESPACE == "libeigen"
