 # Push a nightly tag if the pipeline succeeded.
deploy:tag:nightly:
  stage: deploy
  image: alpine:edge
  dependencies: []
  before_script:
    - apk add git
  script:
    - git tag -f nightly $CI_COMMIT_SHORT_SHA
    - git push -f $EIGEN_CI_GIT_PUSH_URL tag nightly
  tags:
    - linux
    - eigen-runner
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $CI_PROJECT_NAMESPACE == "libeigen"
    - if: $CI_PIPELINE_SOURCE == "web" && $CI_PROJECT_NAMESPACE == "libeigen"

# deploy:docs:
#   stage: deploy
#   image: alpine:edge
#   dependencies: []
#   needs: [ build:linux:cross:x86-64:clang-12:doc ]
#   pages:
#     path_prefix: dox-nightly
#     expire_in: never
#   artifacts:
#     name: "$CI_JOB_NAME_SLUG-$CI_COMMIT_REF_SLUG"
#     paths:
#       - ${EIGEN_CI_BUILDDIR}/doc/html
#   tags:
#     - linux
#     - eigen-runner
#   rules:
#     - if: $CI_PIPELINE_SOURCE == "schedule" && $CI_PROJECT_NAMESPACE == "libeigen"
#     - if: $CI_PIPELINE_SOURCE == "web" && $CI_PROJECT_NAMESPACE == "libeigen"
#     - if: $CI_PIPELINE_SOURCE == "merge_request_event"

