 # Push a nightly tag if the pipeline succeeded.
deploy:tag:nightly:
  stage: deploy
  image: alpine:edge
  dependencies: []
  before_script:
    - apk add git
  script:
    - git tag -f nightly $CI_COMMIT_SHORT_SHA
    - git push -f $EIGEN_CI_GIT_PUSH_URL tag nightly
  tags:
    - linux
    - eigen-runner
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $CI_PROJECT_NAMESPACE == "libeigen"
    - if: $CI_PIPELINE_SOURCE == "web" && $CI_PROJECT_NAMESPACE == "libeigen"

 # Upload docs if pipeline succeeded.
pages:
  stage: deploy
  image: busybox
  dependencies: [ build:linux:doc ]
  script:
    - echo "Deploying site to $CI_PAGES_URL"
    - mv ${EIGEN_CI_BUILDDIR}/doc/html public
  artifacts:
    paths:
      - public
  tags:
    - linux
    - eigen-runner
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $CI_PROJECT_NAMESPACE == "libeigen"
    - if: $CI_PIPELINE_SOURCE == "web" && $CI_PROJECT_NAMESPACE == "libeigen"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
